coverage:
  status:
    project:
      default:
        # basic
        target: 70%
        threshold: 2%
        if_ci_failed: error

comment:
  layout: " diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
