name: Release

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  documentation:
    name: Publish documentation
    needs: version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: current

      - name: Cache konan dependencies
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/libs.versions.toml')}}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Generate docs
        run: ./gradlew :docs:dokkaGenerate -PlibVersion=${{ needs.version.outputs.version }} --no-parallel

      - name: Publish documentation
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          BRANCH: gh-pages
          FOLDER: docs/build/dokka